PurpleBotName: ""
PurpleChannel: ""
RegexCheckFile: ""
MaxQueueSize: 50
WipeMsg: 
  - "This sign has"
  - "been wiped by the"
  - "MC Team!"
  - ""
databaseHost: "localhost"
databasePort: 1433
databaseName: "OpWatch"
databaseUser: "opwatch"
databasePass: "pass.opwatch"